"""Add auto_create_debt field to RecurringPayment

Revision ID: 9131cd61fc64
Revises: 
Create Date: 2026-01-08 06:28:04.020970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9131cd61fc64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем столбец как nullable со значением по умолчанию
    with op.batch_alter_table('recurring_payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_create_debt', sa.Boolean(), nullable=True, server_default='0'))

    # Обновляем существующие записи
    op.execute("UPDATE recurring_payment SET auto_create_debt = 0 WHERE auto_create_debt IS NULL")

    # Делаем столбец NOT NULL
    with op.batch_alter_table('recurring_payment', schema=None) as batch_op:
        batch_op.alter_column('auto_create_debt', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_payment', schema=None) as batch_op:
        batch_op.drop_column('auto_create_debt')

    # ### end Alembic commands ###
