"""Add banking and securities modules

Revision ID: 3a8b4c1d9e0f
Revises: a2c9a7a0d58e
Create Date: 2025-07-30 02:15:10.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a8b4c1d9e0f'
down_revision = 'a2c9a7a0d58e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('translation_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_hash', sa.String(length=32), nullable=False),
    sa.Column('source_lang', sa.String(length=10), nullable=False),
    sa.Column('target_lang', sa.String(length=10), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_hash', 'source_lang', 'target_lang', name='_source_hash_lang_uc')
    )
    with op.batch_alter_table('translation_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_translation_cache_source_hash'), ['source_hash'], unique=False)

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_limit', sa.Numeric(precision=20, scale=2), nullable=True))
        batch_op.add_column(sa.Column('api_secret', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('passphrase', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('other_credentials_json', sa.Text(), nullable=True))

        batch_op.add_column(sa.Column('grace_period_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bank_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_account_bank', 'bank', ['bank_id'], ['id'])

    with op.batch_alter_table('banking_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('to_amount', sa.Numeric(precision=20, scale=2), nullable=True))
        batch_op.add_column(sa.Column('merchant', sa.String(length=255), nullable=True))

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('_name_type_uc', type_='unique')
        batch_op.create_unique_constraint('_name_parent_type_uc', ['name', 'parent_id', 'type'])
        batch_op.create_foreign_key('fk_category_parent', 'category', ['parent_id'], ['id'])

    op.create_table('transaction_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=3), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['banking_transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_item')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint('fk_category_parent', type_='foreignkey')
        batch_op.drop_constraint('_name_parent_type_uc', type_='unique')
        batch_op.create_unique_constraint('_name_type_uc', ['name', 'type'])
        batch_op.drop_column('parent_id')

    with op.batch_alter_table('banking_transaction', schema=None) as batch_op:
        batch_op.drop_column('merchant')
        batch_op.drop_column('to_amount')

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint('fk_account_bank', type_='foreignkey')
        batch_op.drop_column('bank_id')
        batch_op.drop_column('other_credentials_json')
        batch_op.drop_column('passphrase')
        batch_op.drop_column('api_secret')

        batch_op.drop_column('grace_period_days')
        batch_op.drop_column('credit_limit')

    with op.batch_alter_table('translation_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_translation_cache_source_hash'))

    op.drop_table('translation_cache')
    op.drop_table('bank')
    # ### end Alembic commands ###