"""Add parent_id to Account model for sub-accounts

Revision ID: 11864aaf0ae0
Revises: e2b382f21a07
Create Date: 2025-11-17 23:51:46.420102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11864aaf0ae0'
down_revision = 'e2b382f21a07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_account_parent_id', 'account', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint('fk_account_parent_id', type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
