"""empty message

Revision ID: 695a643d9d8e
Revises: a1052ab0c620
Create Date: 2025-10-05 16:15:17.249660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '695a643d9d8e'
down_revision = 'a1052ab0c620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('next_due_date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investment_platform', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_secret', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('passphrase', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('other_credentials_json', sa.Text(), nullable=True))
        batch_op.drop_column('other_credentials_json_encrypted')
        batch_op.drop_column('api_secret_encrypted')
        batch_op.drop_column('passphrase_encrypted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_platform', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passphrase_encrypted', sa.VARCHAR(length=512), nullable=True))
        batch_op.add_column(sa.Column('api_secret_encrypted', sa.VARCHAR(length=512), nullable=True))
        batch_op.add_column(sa.Column('other_credentials_json_encrypted', sa.TEXT(), nullable=True))
        batch_op.drop_column('other_credentials_json')
        batch_op.drop_column('passphrase')
        batch_op.drop_column('api_secret')

    op.drop_table('recurring_payment')
    # ### end Alembic commands ###
