"""Add new models and update existing ones

Revision ID: a1052ab0c620
Revises: e5a9c8d7b6f0
Create Date: 2025-08-21 23:03:47.552142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1052ab0c620'
down_revision = 'e5a9c8d7b6f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crypto_portfolio_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_history_date'))
        batch_op.create_index(batch_op.f('ix_crypto_portfolio_history_date'), ['date'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crypto_portfolio_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crypto_portfolio_history_date'))
        batch_op.create_index(batch_op.f('ix_portfolio_history_date'), ['date'], unique=1)

    # ### end Alembic commands ###
