"""Add TranslationCache table

Revision ID: ad1253078ee9
Revises: f6g5h4i3j2k1
Create Date: 2025-08-14 18:44:39.830536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad1253078ee9'
down_revision = 'f6g5h4i3j2k1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_hash', sa.String(length=32), nullable=False),
    sa.Column('source_lang', sa.String(length=10), nullable=False),
    sa.Column('target_lang', sa.String(length=10), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_hash', 'source_lang', 'target_lang', name='_source_hash_lang_uc')
    )
    with op.batch_alter_table('translation_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_translation_cache_source_hash'), ['source_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translation_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_translation_cache_source_hash'))

    op.drop_table('translation_cache')
    # ### end Alembic commands ###
