"""Add is_external to Account model for external accounts

Revision ID: e1819bae444b
Revises: 11864aaf0ae0
Create Date: 2025-11-18 06:41:20.095821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1819bae444b'
down_revision = '11864aaf0ae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_external', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('is_external')

    # ### end Alembic commands ###
