"""Rename portfolio_history to crypto_portfolio_history

Revision ID: e5a9c8d7b6f0
Revises: ad1253078ee9
Create Date: 2025-08-20 14:10:00.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5a9c8d7b6f0'
down_revision = 'ad1253078ee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('portfolio_history', 'crypto_portfolio_history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('crypto_portfolio_history', 'portfolio_history')
    # ### end Alembic commands ###