"""add interval_value to recurring_payment

Revision ID: e89840caea24
Revises: e1819bae444b
Create Date: 2025-11-19 09:27:26.928014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e89840caea24'
down_revision = 'e1819bae444b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interval_value', sa.Integer(), nullable=True))

    op.execute("UPDATE recurring_payment SET interval_value = 1 WHERE interval_value IS NULL")

    with op.batch_alter_table('recurring_payment', schema=None) as batch_op:
        batch_op.alter_column('interval_value', existing_type=sa.Integer(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_payment', schema=None) as batch_op:
        batch_op.drop_column('interval_value')

    # ### end Alembic commands ###
