"""add category_id to recurring_payment and recurring_payment_id to debt

Revision ID: f8a9b0c1d2e3
Revises: e89840caea24
Create Date: 2025-11-22 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8a9b0c1d2e3'
down_revision = 'e89840caea24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('debt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurring_payment_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debt', schema=None) as batch_op:
        batch_op.drop_column('recurring_payment_id')

    with op.batch_alter_table('recurring_payment', schema=None) as batch_op:
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###